apiVersion: v1
kind: Secret
metadata:
  name: auth-root-login-secret
  namespace: %KUBERNETES_NAMESPACE%
type: Opaque
stringData:
  root-login-username: %AUTH_ROOT_LOGIN_USERNAME%
  root-login-password: %AUTH_ROOT_LOGIN_PASSWORD%
