services:
  api.storage.local:
    image: api.storage.local
    hostname: api-storage-local
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.Storage.Local
      dockerfile: "Dockerfile.Local"
    networks:
      - network
    volumes:
      - ./bin/nano-storage-local:/mnt/nano-storage-local

networks:
  network:
    name: network
    driver: bridge
