services:
  api.custommiddleware:
    image: api.custommiddleware
    hostname: api-custommiddleware
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.CustomMiddleware
      dockerfile: "Dockerfile.Local"
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
