services:
  api.data.postgresql.spatial:
    image: api.data.postgresql.spatial
    hostname: api-data-postgresql-spatial
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.Data.PostgreSQL.Spatial
      dockerfile: "Dockerfile.Local"
    depends_on:
      - database
    networks:
      - network

  database:
    image: postgis/postgis:latest
    ports:
      - 5432:5432
    networks:
      - network
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: myPassword_123
      POSTGRES_DB: nanoDb

networks:
  network:
    name: network
    driver: bridge
