services:
  api.documentation.nonce:
    image: api.documentation.nonce
    hostname: api-documentation.nonce
    restart: on-failure
    ports:
      - 8080:8080
      - 4443:4443
    build:
      context: ../Api.Documentation.Nonce
      dockerfile: "Dockerfile.Local"
    volumes:
      - ../:/root/.dotnet/https
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
