services:
  api.auth.rootlogin:
    image: api.auth.rootlogin
    hostname: api-auth-rootlogin
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.Auth.RootLogin
      dockerfile: "Dockerfile.Local"
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
