services:
  api.data.mysql.spatial:
    image: api.data.mysql.spatial
    hostname: api-data-mysql-spatial
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.Data.MySql.Spatial
      dockerfile: "Dockerfile.Local"
    depends_on:
      - database
    networks:
      - network

  database:
    image: mysql/mysql-server:latest
    ports:
      - 3306:3306
    networks:
      - network
    environment:
      MYSQL_USER: sa
      MYSQL_PASSWORD: myPassword_123
      MYSQL_ROOT_PASSWORD: myPassword_123
      MYSQL_DATABASE: nanoDb
      MYSQL_ROOT_HOST: '%'

networks:
  network:
    name: network
    driver: bridge
