services:
  api.data.identity:
    image: api.data.identity
    hostname: api-data-identity
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.Data.Identity
      dockerfile: "Dockerfile.Local"
    depends_on:
      - database
    networks:
      - network

  database:
    image: mysql/mysql-server:latest
    ports:
      - 3306:3306
    networks:
      - network
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: myPassword_123

networks:
  network:
    name: network
    driver: bridge
