services:
  api.policyheaders.xssprotection:
    image: api.policyheaders.xssprotection
    hostname: api-policyheaders-xssprotection
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.PolicyHeaders.XssProtection
      dockerfile: "Dockerfile.Local"
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge