services:
  api.logging.log4net:
    image: api.logging.log4net
    hostname: api-logging-log4net
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.Logging.Log4Net
      dockerfile: "Dockerfile.Local"
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
