CREATE DATABASE IF NOT EXISTS nanoDb;
CREATE DATABASE IF NOT EXISTS nanoDb2;

CREATE USER 'sa'@'%' IDENTIFIED BY 'myPassword_123';

GRANT ALL PRIVILEGES ON nanoDb.* TO 'sa'@'%';
GRANT ALL PRIVILEGES ON nanoDb2.* TO 'sa'@'%';

FLUSH PRIVILEGES;