services:
  api.timezone:
    image: api.timezone
    hostname: api-timezone
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.TimeZone
      dockerfile: "Dockerfile.Local"
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
