services:
  api.logging.microsoft:
    image: api.logging.microsoft
    hostname: api-logging-microsoft
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.Logging.Microsoft
      dockerfile: "Dockerfile.Local"
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
