services:
  console.scopeddependencies:
    image: console.scopeddependencies
    restart: on-failure
    build:
      context: ../Console.ScopedDependencies
      dockerfile: "Dockerfile.Local"
    networks:
      - network

networks:
  network:
    name: network
    external: true
