apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: %SERVICE_NAME%-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: %SERVICE_NAME%-storage-class
  resources:
    requests:
      storage: %STORAGE_SIZE%