services:
  api.hosting.multipartlimits:
    image: api.hosting.multipartlimits
    hostname: api-hosting-multipartlimits
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.Hosting.MultipartLimits
      dockerfile: "Dockerfile.Local"
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
