services:
  api.blank:
    image: api.blank
    hostname: api-blank
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.Blank
      dockerfile: "Dockerfile.Local"
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
