services:
  api.data.sqlite:
    image: api.data.postgresql.spatial
    hostname: api-data-postgresql-spatial
    build:
      context: ../Api.Data.SqLite
      dockerfile: Dockerfile.Local
    hostname: api-data-sqlite
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - ./bin/data:/data
    networks:
      - network

networks:
  network:
    driver: bridge