services:
  console.blank:
    image: console.blank
    restart: on-failure
    build:
      context: ../Console.Blank
      dockerfile: "Dockerfile.Local"
    env_file:
      - .env
    networks:
      - network

networks:
  network:
    name: network
    external: true
