services:
  api.documentation:
    image: api.documentation
    hostname: api-documentation
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.Documentation
      dockerfile: "Dockerfile.Local"
    env_file:
      - .env
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
