services:
  api.responsecompression:
    image: api.responsecompression
    hostname: api-responsecompression
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.ResponseCompression
      dockerfile: "Dockerfile.Local"
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
