services:
  api.errorhandling:
    image: api.errorhandling
    hostname: api-errorhandling
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.ErrorHandling
      dockerfile: "Dockerfile.Local"
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge