services:
  api.data.repository.audit:
    image: api.data.repository.audit
    hostname: api-data-audit
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.Data.Audit
      dockerfile: "Dockerfile.Local"
    depends_on:
      - database
    networks:
      - network

  database:
    image: mysql/mysql-server:latest
    ports:
      - 3306:3306
    networks:
      - network
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: myPassword_123

networks:
  network:
    name: network
    driver: bridge
