services:
  api.contentnegotiation:
    image: api.contentnegotiation
    hostname: api-contentnegotiation
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.ContentNegotiation
      dockerfile: "Dockerfile.Local"
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
