services:
  api.apiclients.audit:
    image: api.apiclients.audit
    hostname: api-apiclients-audit
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.ApiClients.Audit
      dockerfile: "Dockerfile.Local"
    networks:
      - network

  api.apiclients.audit.service:
    image: api.apiclients.audit.service
    hostname: api-apiclients-audit-service
    restart: on-failure
    ports:
      - 8181:8181
    build:
      context: ../Api.ApiClients.Audit.Service
      dockerfile: "Dockerfile.Local"
    depends_on:
      - database
    networks:
      - network

  database:
    image: mysql/mysql-server:latest
    ports:
      - 3306:3306
    networks:
      - network
    environment:
      MYSQL_USER: sa
      MYSQL_PASSWORD: myPassword_123
      MYSQL_ROOT_PASSWORD: myPassword_123
      MYSQL_DATABASE: nanoDb
      MYSQL_ROOT_HOST: '%'

networks:
  network:
    name: network
    driver: bridge
