apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: %SERVICE_NAME%-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: %SERVICE_NAME%-data-storage-class
  resources:
    requests:
      storage: %DATA_SIZE%