services:
  console.workers:
    image: console.workers
    restart: on-failure
    build:
      context: ../Console.Workers
      dockerfile: "Dockerfile.Local"
    networks:
      - network

networks:
  network:
    name: network
    external: true
