services:
  console.storage.local:
    image: console.storage.local
    restart: on-failure
    build:
      context: ../Console.Storage.Local
      dockerfile: "Dockerfile.Local"
    networks:
      - network
    volumes:
      - ./bin/nano-storage-local:/mnt/nano-storage-local

networks:
  network:
    name: network
    external: true
