services:
  api.storage.azure:
    image: api.storage.azure
    hostname: api-storage-azure
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.Storage.Azure
      dockerfile: "Dockerfile.Local"
    networks:
      - network
    volumes:
      - ./bin/nano-storage-azure:/mnt/nano-storage-azure

networks:
  network:
    name: network
    driver: bridge
