services:
  console.localization:
    image: console.localization
    restart: on-failure
    build:
      context: ../Console.Localization
      dockerfile: "Dockerfile.Local"
    env_file:
      - .env
    networks:
      - network

networks:
  network:
    name: network
    external: true
