services:
  console.storage.azure:
    image: console.storage.azure
    restart: on-failure
    build:
      context: ../Console.Storage.Azure
      dockerfile: "Dockerfile.Local"
    networks:
      - network
    volumes:
      - ./bin/nano-storage-azure:/mnt/nano-storage-azure

networks:
  network:
    name: network
    external: true
