services:
  api.startuptasks:
    image: api.startuptasks
    hostname: api-startuptasks
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ../Api.StartupTasks
      dockerfile: "Dockerfile.Local"
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
