services:
  console.customconfigsection:
    image: console.customconfigsection
    restart: on-failure
    build:
      context: ../Console.CustomConfigSection
      dockerfile: "Dockerfile.Local"
    networks:
      - network

networks:
  network:
    name: network
    external: true
